// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var InkEmailGenerator, path, util, yeoman;

  util = require('util');

  path = require('path');

  yeoman = require('yeoman-generator');

  InkEmailGenerator = module.exports = function(args, options, config) {
    yeoman.generators.Base.apply(this, arguments);
    return this.on('end', function() {
      return this.installDependencies({
        skipInstall: options['skip-install']
      });
    });
  };

  util.inherits(InkEmailGenerator, yeoman.generators.Base);

  InkEmailGenerator.prototype.askFor = function() {
    var cb, prompts;
    cb = this.async();
    prompts = [];
    return this.prompt(prompts, (function(props) {
      var key, val;
      for (key in props) {
        val = props[key];
        this[key] = val;
      }
      return cb();
    }).bind(this));
  };

  InkEmailGenerator.prototype.files = function() {
    this.copy('_package.json', 'package.json');
    this.copy('_bower.json', 'bower.json');
    this.copy('_Gruntfile.coffee', 'Gruntfile.coffee');
    this.mkdir('src');
    this.mkdir('build');
    this.copy('_email.jade', 'src/email.jade');
    this.copy('_layout.jade', 'src/_layout.jade');
    return this.copy('_mixins.jade', 'src/_mixins.jade');
  };

}).call(this);
